version: '2'
services:
  web:
    build: .
    command: python app/app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/finance
    depends_on:
      - db
    restart: always
  db:
    image: mongo
    # volumes:
    # - ./db/:/data/db
